### ISSUE TITLE
[Article] Register a smart contract to the SFS with Foundry

### ISSUE THREAD

**Issue by joshuanwankwo** [mode-network/mode-cooperators#14]
## Task Description:
Write an article on how to register a smart contract to the SFS using Foundry.

## Acceptance Criteria:
- Length and Depth: Minimum of 800 words, ensuring in-depth coverage of the topic.
- Formatting: Clear structure with headings, subheadings, and bullet points for easy reading.
- Visuals: This is not a must, but it's a plus if it includes relevant images, diagrams, or code snippets where applicable.
- Language and Style: Professional, engaging, and free of grammatical errors.

## Resources and References:
https://docs.mode.network/build-on-mode/tutorials/interacting-with-smart-contracts-using-ethers.js

**Comment by joshfrommode** [comment]
Hi @fede2442 @joshuanwankwo please assign this task to me

**Comment by joshfrommode** [comment]
Hey @joshuanwankwo @fede2442 please assign this task to me

**Comment by joshuanwankwo** [comment]
Done

**Comment by joshfrommode** [comment]
Done #35

**Comment by joshfrommode** [comment]
Done #35
