### ISSUE TITLE
[Video] How to bridge asset from Ethereum to Mode

### ISSUE THREAD

**Issue by joshuanwankwo** [mode-network/mode-cooperators#48]
Will update details soon.

## Task Description:
Provide a clear and concise description of the task.
Explain the purpose and expected outcome of this task.

## Acceptance Criteria:
List the criteria that must be met for the task to be considered complete.
Include any specific performance or quality requirements.

## Resources and References:
Provide links to any relevant documentation, articles, or code repositories.
Mention similar tasks or examples, if any.

**Comment by wolfcito** [comment]
Hey @joshuanwankwo I would like to do this task in spanish 🚀 could you assign me pls
